# Compile stage
FROM golang:1.19 AS build-env

COPY ./proto/ /dockerdev/proto
COPY ./core/ /dockerdev/core
COPY ./fs-server/ /dockerdev/fs-server

WORKDIR /dockerdev/fs-server

RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -gcflags="all=-N -l" -o /server

# Final stage
FROM alpine:latest

EXPOSE 50000

WORKDIR /
COPY --from=build-env /server /

CMD ["/server"]
