// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: activity.proto

package activity

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ActivityManagerClient is the client API for ActivityManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ActivityManagerClient interface {
	RegisterUserActivity(ctx context.Context, in *RegisterUserActivityRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	RegisterGsActivity(ctx context.Context, in *RegisterGsActivityRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type activityManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewActivityManagerClient(cc grpc.ClientConnInterface) ActivityManagerClient {
	return &activityManagerClient{cc}
}

func (c *activityManagerClient) RegisterUserActivity(ctx context.Context, in *RegisterUserActivityRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/activity.ActivityManager/RegisterUserActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityManagerClient) RegisterGsActivity(ctx context.Context, in *RegisterGsActivityRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/activity.ActivityManager/RegisterGsActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivityManagerServer is the server API for ActivityManager service.
// All implementations must embed UnimplementedActivityManagerServer
// for forward compatibility
type ActivityManagerServer interface {
	RegisterUserActivity(context.Context, *RegisterUserActivityRequest) (*empty.Empty, error)
	RegisterGsActivity(context.Context, *RegisterGsActivityRequest) (*empty.Empty, error)
	mustEmbedUnimplementedActivityManagerServer()
}

// UnimplementedActivityManagerServer must be embedded to have forward compatible implementations.
type UnimplementedActivityManagerServer struct {
}

func (UnimplementedActivityManagerServer) RegisterUserActivity(context.Context, *RegisterUserActivityRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUserActivity not implemented")
}
func (UnimplementedActivityManagerServer) RegisterGsActivity(context.Context, *RegisterGsActivityRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterGsActivity not implemented")
}
func (UnimplementedActivityManagerServer) mustEmbedUnimplementedActivityManagerServer() {}

// UnsafeActivityManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActivityManagerServer will
// result in compilation errors.
type UnsafeActivityManagerServer interface {
	mustEmbedUnimplementedActivityManagerServer()
}

func RegisterActivityManagerServer(s grpc.ServiceRegistrar, srv ActivityManagerServer) {
	s.RegisterService(&ActivityManager_ServiceDesc, srv)
}

func _ActivityManager_RegisterUserActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityManagerServer).RegisterUserActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/activity.ActivityManager/RegisterUserActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityManagerServer).RegisterUserActivity(ctx, req.(*RegisterUserActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivityManager_RegisterGsActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterGsActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityManagerServer).RegisterGsActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/activity.ActivityManager/RegisterGsActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityManagerServer).RegisterGsActivity(ctx, req.(*RegisterGsActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ActivityManager_ServiceDesc is the grpc.ServiceDesc for ActivityManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ActivityManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "activity.ActivityManager",
	HandlerType: (*ActivityManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUserActivity",
			Handler:    _ActivityManager_RegisterUserActivity_Handler,
		},
		{
			MethodName: "RegisterGsActivity",
			Handler:    _ActivityManager_RegisterGsActivity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "activity.proto",
}
