// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: authentication.proto

package authentication

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	jwt "iceline-hosting.com/backend/proto/jwt"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthenticationClient is the client API for Authentication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthenticationClient interface {
	VerifyGrpc(ctx context.Context, in *jwt.JWT, opts ...grpc.CallOption) (*VerifiedState, error)
	RegenerateJwtGrpc(ctx context.Context, in *jwt.JWT, opts ...grpc.CallOption) (*jwt.JWT, error)
}

type authenticationClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthenticationClient(cc grpc.ClientConnInterface) AuthenticationClient {
	return &authenticationClient{cc}
}

func (c *authenticationClient) VerifyGrpc(ctx context.Context, in *jwt.JWT, opts ...grpc.CallOption) (*VerifiedState, error) {
	out := new(VerifiedState)
	err := c.cc.Invoke(ctx, "/authentication.Authentication/VerifyGrpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationClient) RegenerateJwtGrpc(ctx context.Context, in *jwt.JWT, opts ...grpc.CallOption) (*jwt.JWT, error) {
	out := new(jwt.JWT)
	err := c.cc.Invoke(ctx, "/authentication.Authentication/RegenerateJwtGrpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticationServer is the server API for Authentication service.
// All implementations must embed UnimplementedAuthenticationServer
// for forward compatibility
type AuthenticationServer interface {
	VerifyGrpc(context.Context, *jwt.JWT) (*VerifiedState, error)
	RegenerateJwtGrpc(context.Context, *jwt.JWT) (*jwt.JWT, error)
	mustEmbedUnimplementedAuthenticationServer()
}

// UnimplementedAuthenticationServer must be embedded to have forward compatible implementations.
type UnimplementedAuthenticationServer struct {
}

func (UnimplementedAuthenticationServer) VerifyGrpc(context.Context, *jwt.JWT) (*VerifiedState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyGrpc not implemented")
}
func (UnimplementedAuthenticationServer) RegenerateJwtGrpc(context.Context, *jwt.JWT) (*jwt.JWT, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegenerateJwtGrpc not implemented")
}
func (UnimplementedAuthenticationServer) mustEmbedUnimplementedAuthenticationServer() {}

// UnsafeAuthenticationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthenticationServer will
// result in compilation errors.
type UnsafeAuthenticationServer interface {
	mustEmbedUnimplementedAuthenticationServer()
}

func RegisterAuthenticationServer(s grpc.ServiceRegistrar, srv AuthenticationServer) {
	s.RegisterService(&Authentication_ServiceDesc, srv)
}

func _Authentication_VerifyGrpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(jwt.JWT)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServer).VerifyGrpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authentication.Authentication/VerifyGrpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServer).VerifyGrpc(ctx, req.(*jwt.JWT))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authentication_RegenerateJwtGrpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(jwt.JWT)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServer).RegenerateJwtGrpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authentication.Authentication/RegenerateJwtGrpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServer).RegenerateJwtGrpc(ctx, req.(*jwt.JWT))
	}
	return interceptor(ctx, in, info, handler)
}

// Authentication_ServiceDesc is the grpc.ServiceDesc for Authentication service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Authentication_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "authentication.Authentication",
	HandlerType: (*AuthenticationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyGrpc",
			Handler:    _Authentication_VerifyGrpc_Handler,
		},
		{
			MethodName: "RegenerateJwtGrpc",
			Handler:    _Authentication_RegenerateJwtGrpc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authentication.proto",
}
