name: Publish fs-server to GHCR

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/shashwat5050/fs-server:latest -f Dockerfile-fs-server . --push
          docker login ghcr.io -u shashwat5050 -p ${{secrets.GHCR_SECRET_TOKEN }}
          docker push ghcr.io/shashwat5050/fs-server:latest
        env:
          DOCKER_CLI: docker
